name: Scheduled Tasks

on:
  schedule:
    # 毎日午前9時（JST）にタスクチェック実行 (UTC 0:00)
    - cron: '0 0 * * *'
    # 毎日午前6時（JST）に支払いリマインダー実行 (UTC 21:00前日)
    - cron: '0 21 * * *'
    # 毎週月曜日午前10時（JST）に週次レポート実行 (UTC 1:00)
    - cron: '0 1 * * 1'

  # 手動実行も可能にする
  workflow_dispatch:
    inputs:
      function_name:
        description: 'Function to run (daily-task-check, payment-reminder, weekly-report, or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - daily-task-check
          - payment-reminder
          - weekly-report

jobs:
  daily-task-check:
    name: Daily Task Check
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * *' || github.event.inputs.function_name == 'daily-task-check' || github.event.inputs.function_name == 'all'

    steps:
      - name: Invoke Daily Task Check Function
        run: |
          curl -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/daily-task-check" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

  payment-reminder:
    name: Payment Reminder
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 21 * * *' || github.event.inputs.function_name == 'payment-reminder' || github.event.inputs.function_name == 'all'

    steps:
      - name: Invoke Payment Reminder Function
        run: |
          curl -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/payment-reminder" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

  weekly-report:
    name: Weekly Report
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 1 * * 1' || github.event.inputs.function_name == 'weekly-report' || github.event.inputs.function_name == 'all'

    steps:
      - name: Invoke Weekly Report Function
        run: |
          curl -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/weekly-report" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
